/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vanan Andreas
 */
public class calcu extends javax.swing.JFrame {

    int x = 0, y = 0, z = 0, mem;
    char op;

    public calcu() {
        initComponents();
        this.setLocationRelativeTo(getRootPane());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tombol1 = new javax.swing.JButton();
        tombol4 = new javax.swing.JButton();
        tombol7 = new javax.swing.JButton();
        tombol2 = new javax.swing.JButton();
        tombol5 = new javax.swing.JButton();
        tombol8 = new javax.swing.JButton();
        tombol3 = new javax.swing.JButton();
        tombol6 = new javax.swing.JButton();
        tombol9 = new javax.swing.JButton();
        tombolhapus = new javax.swing.JButton();
        tombolmemin = new javax.swing.JButton();
        tombolmemout = new javax.swing.JButton();
        tombolsamadengan = new javax.swing.JButton();
        tombol0 = new javax.swing.JButton();
        tomboltambah = new javax.swing.JButton();
        tombolkurang = new javax.swing.JButton();
        tombolkali = new javax.swing.JButton();
        tombolbagi = new javax.swing.JButton();
        field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tombol1.setText("1");
        tombol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol1ActionPerformed(evt);
            }
        });

        tombol4.setText("4");
        tombol4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol4ActionPerformed(evt);
            }
        });

        tombol7.setText("7");
        tombol7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol7ActionPerformed(evt);
            }
        });

        tombol2.setText("2");
        tombol2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol2ActionPerformed(evt);
            }
        });

        tombol5.setText("5");
        tombol5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol5ActionPerformed(evt);
            }
        });

        tombol8.setText("8");
        tombol8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol8ActionPerformed(evt);
            }
        });

        tombol3.setText("3");
        tombol3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol3ActionPerformed(evt);
            }
        });

        tombol6.setText("6");
        tombol6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol6ActionPerformed(evt);
            }
        });

        tombol9.setText("9");
        tombol9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol9ActionPerformed(evt);
            }
        });

        tombolhapus.setText("Hapus");
        tombolhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolhapusActionPerformed(evt);
            }
        });

        tombolmemin.setText("Mem In");
        tombolmemin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolmeminActionPerformed(evt);
            }
        });

        tombolmemout.setText("Mem Out");
        tombolmemout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolmemoutActionPerformed(evt);
            }
        });

        tombolsamadengan.setText("=");
        tombolsamadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolsamadenganActionPerformed(evt);
            }
        });

        tombol0.setText("0");
        tombol0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol0ActionPerformed(evt);
            }
        });

        tomboltambah.setText("+");
        tomboltambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboltambahActionPerformed(evt);
            }
        });

        tombolkurang.setText("-");
        tombolkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolkurangActionPerformed(evt);
            }
        });

        tombolkali.setText("*");
        tombolkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolkaliActionPerformed(evt);
            }
        });

        tombolbagi.setText("/");
        tombolbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbagiActionPerformed(evt);
            }
        });

        field.setDisabledTextColor(new java.awt.Color(187, 187, 187));
        field.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(field)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tombol1)
                            .addComponent(tombol4)
                            .addComponent(tombol7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tombol2)
                                    .addComponent(tombol5)
                                    .addComponent(tombol8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tombol3)
                                    .addComponent(tombol6)
                                    .addComponent(tombol9)))
                            .addComponent(tombol0))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tombolmemout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tombolmemin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tombolhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tombolsamadengan, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tombolbagi)
                            .addComponent(tomboltambah)
                            .addComponent(tombolkurang)
                            .addComponent(tombolkali))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tombol3)
                                .addGap(18, 18, 18)
                                .addComponent(tombol6)
                                .addGap(18, 18, 18)
                                .addComponent(tombol9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tombol2)
                                .addGap(18, 18, 18)
                                .addComponent(tombol5)
                                .addGap(18, 18, 18)
                                .addComponent(tombol8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tombol1)
                                .addGap(18, 18, 18)
                                .addComponent(tombol4)
                                .addGap(18, 18, 18)
                                .addComponent(tombol7)))
                        .addGap(18, 18, 18)
                        .addComponent(tombol0))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tombolhapus)
                                .addGap(18, 18, 18)
                                .addComponent(tombolmemin)
                                .addGap(18, 18, 18)
                                .addComponent(tombolmemout))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tomboltambah)
                                .addGap(18, 18, 18)
                                .addComponent(tombolkurang)
                                .addGap(18, 18, 18)
                                .addComponent(tombolkali)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tombolsamadengan)
                            .addComponent(tombolbagi))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolhapusActionPerformed
        field.setText(null);
    }//GEN-LAST:event_tombolhapusActionPerformed

    private void tomboltambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboltambahActionPerformed
        field.setText(field.getText() + "+");
        op = '+';
    }//GEN-LAST:event_tomboltambahActionPerformed

    private void tombol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol1ActionPerformed
        field.setText(field.getText() + "1");
    }//GEN-LAST:event_tombol1ActionPerformed

    private void tombol2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol2ActionPerformed
        field.setText(field.getText() + "2");
    }//GEN-LAST:event_tombol2ActionPerformed

    private void tombol3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol3ActionPerformed
        field.setText(field.getText() + "3");
    }//GEN-LAST:event_tombol3ActionPerformed

    private void tombol4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol4ActionPerformed
        field.setText(field.getText() + "4");
    }//GEN-LAST:event_tombol4ActionPerformed

    private void tombol5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol5ActionPerformed
        field.setText(field.getText() + "5");
    }//GEN-LAST:event_tombol5ActionPerformed

    private void tombol6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol6ActionPerformed
        field.setText(field.getText() + "6");
    }//GEN-LAST:event_tombol6ActionPerformed

    private void tombol7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol7ActionPerformed
        field.setText(field.getText() + "7");
    }//GEN-LAST:event_tombol7ActionPerformed

    private void tombol8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol8ActionPerformed
        field.setText(field.getText() + "8");
    }//GEN-LAST:event_tombol8ActionPerformed

    private void tombol9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol9ActionPerformed
        field.setText(field.getText() + "9");
    }//GEN-LAST:event_tombol9ActionPerformed

    private void tombol0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol0ActionPerformed
        field.setText(field.getText() + "0");
    }//GEN-LAST:event_tombol0ActionPerformed

    private void tombolkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolkurangActionPerformed
        field.setText(field.getText() + "-");
        op = '-';
    }//GEN-LAST:event_tombolkurangActionPerformed

    private void tombolkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolkaliActionPerformed
        field.setText(field.getText() + "*");
        op = '*';
    }//GEN-LAST:event_tombolkaliActionPerformed

    private void tombolbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbagiActionPerformed
        field.setText(field.getText() + "/");
        op = '/';
    }//GEN-LAST:event_tombolbagiActionPerformed

    private void tombolsamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolsamadenganActionPerformed
        String left, right;
        try {
            left = field.getText().substring(0, field.getText().indexOf(op + ""));
            right = field.getText().substring(field.getText().indexOf(op + "") + 1, field.getText().length());
            switch (op) {
                case '+':
                    field.setText("" + ((Integer.parseInt(left)) + Integer.parseInt(right)));
                    break;
                case '-':
                    field.setText("" + ((Integer.parseInt(left)) - Integer.parseInt(right)));
                    break;
                case '/':
                    field.setText("" + ((Integer.parseInt(left)) / Integer.parseInt(right)));
                    break;
                case '*':
                    field.setText("" + ((Integer.parseInt(left)) * Integer.parseInt(right)));
                    break;
                default:
                    field.setText("ERR");
                    ;
                    break;
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_tombolsamadenganActionPerformed

    private void tombolmeminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolmeminActionPerformed
        if (field.getText().contains("-") || field.getText().contains("+") || field.getText().contains("*") || field.getText().contains("/")) {

            field.setText(null);
        } else {
            mem = Integer.parseInt(field.getText());
            field.setText(null);
        }
    }//GEN-LAST:event_tombolmeminActionPerformed

    private void tombolmemoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolmemoutActionPerformed
        if (mem == 0) {
            field.setText("0");
        } else {
            field.setText(field.getText() + mem);
        }
    }//GEN-LAST:event_tombolmemoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calcu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField field;
    private javax.swing.JButton tombol0;
    private javax.swing.JButton tombol1;
    private javax.swing.JButton tombol2;
    private javax.swing.JButton tombol3;
    private javax.swing.JButton tombol4;
    private javax.swing.JButton tombol5;
    private javax.swing.JButton tombol6;
    private javax.swing.JButton tombol7;
    private javax.swing.JButton tombol8;
    private javax.swing.JButton tombol9;
    private javax.swing.JButton tombolbagi;
    private javax.swing.JButton tombolhapus;
    private javax.swing.JButton tombolkali;
    private javax.swing.JButton tombolkurang;
    private javax.swing.JButton tombolmemin;
    private javax.swing.JButton tombolmemout;
    private javax.swing.JButton tombolsamadengan;
    private javax.swing.JButton tomboltambah;
    // End of variables declaration//GEN-END:variables
}
